# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  cloudinary_api_key: <%= ENV["OHC_CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret_key: <%= ENV["OHC_CLOUDINARY_API_SECRET_KEY"] %>
  secret_key_base: <%= ENV["OHC_SECRET_KEY_BASE"] %>
  secret_key_base: "3d8e523d8812bfcb6f80524cbeb37da810137c7190b37f7849f4b2eaef4d4b67429d80ed58de4f9a25995711f5dbc5e098239ebd4a94cdadea2d43f2a3ecba90"

test:
  secret_key_base: <%= ENV["OHC_SECRET_KEY_BASE_TEST"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret_key: <%= ENV["CLOUDINARY_API_SECRET_KEY"] %>
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUDNAME"] %>
